CONTRIBUTING.md, lib/passageidentity/auth.rb, lib/passageidentity/client.rb, passageidentity.gemspec, tests/auth_test.rb
Added auth-test to test for JWT validation:
- moved fetch_jwks and fetch_app into auth.rb (to streamline the entire flow)
=> update authentication to use jwks

lib/passageidentity/auth.rb, passageidentity.gemspec
=> remove the checking of the JWT issuer in authenticate_token()

README.md
!!! Do not merge until custom email docs are released !!!
=> Update guides path in Gitbook from popular-guides to guides 

.github/workflows/on_pr.yml
**What type of change is this**
This is a testing improvement that has no functional changes to the SDK. 
**Describe this change**
Add a workflow_dispatch trigger to the run test workflow.
=> Chore: Add workflow_dispatch to run test workflow

lib/passageidentity/client.rb, passageidentity.gemspec
-   add sdk version to header
-   reads version from gemspec
[Gem Specification load](https://docs.ruby-lang.org/en/2.5.0/Gem/Specification.html#method-c-load)
=> PSG-1035: add sdk version header

passageidentity.gemspec
=> Fix `source_code_uri` in the gemspec

README.md, lib/passageidentity/client.rb
Provides the ability to get and configure Auth Fallback App Properties.
=> Auth Fallback Method Properties

README.md, docs/custom/AuthApi.md, docs/custom/ClientApi.md, docs/custom/UserApi.md, docs/custom/UsersApi.md, lib/passageidentity/auth.rb
[PSG-3181](https://passage-identity.atlassian.net/browse/PSG-3181)
Create docs for the wrapped functions. All Gitbook docs also link to these docs.
These function names should be the same as they are currently. The in between wrapper layer can be confusing, please double check that I didn't miss anything or mistype. 
[PSG-3181]: https://passage-identity.atlassian.net/browse/PSG-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add wrapper function docs

CHANGELOG.md, generate.sh, lib/passageidentity/user_api.rb, lib/passageidentity/version.rb
Deploy version 0.3.0.
Creates a CHANGELOG file.
=> Deploy v0.3.0 - Create CHANGELOG, update version

CHANGELOG.md, Gemfile, lib/passageidentity/version.rb
Bump version (patch) and update changelog
=> PSG-4788 bump version + changelog

CHANGELOG.md, LICENSE, README.md, lib/passageidentity/version.rb, passageidentity.gemspec
Update to the new README template, updated license, updated metadata in gemspec file.
Add any other context or screenshots about the pull request here.
=> Update Passage-Ruby With New Readme and License

.github/workflows/on-pull-request.yml, .github/workflows/pr-title-check.yml, .rubocop.yml
- adds pr title check to PR CI
- adds linter and formatter to PR CI
- does **not** add a default config file for rubocop since it is almost [6k loc](https://github.com/rubocop/rubocop/blob/master/config/default.yml) and will be inherited automatically by rubocop
=> ci: adds linting and formatting jobs to on pull request workflow

.github/workflows/release-as.yml, .github/workflows/release.yml
This is an extension of #107, adding a "release as" workflow to specify a version number to release as instead of the automatically parsed one from release-please
=> ci: adds release-as workflow

.github/workflows/release-as.yml
=> ci: release-as workflow now pulls all tags correctly and uses a PAT to merge the PR

lib/passageidentity/auth.rb, lib/passageidentity/client.rb, lib/passageidentity/error.rb, lib/passageidentity/user_api.rb
-   set explicit msg precedence in `PassageError`
-   align get-by-identifier error description with other SDKs
-   use symbols in `PassageError` to support both string and symbol keys
-   update handwritten error codes to match auth OpenAPI schema
=> fix: update PassageError message precedence

lib/passageidentity/auth.rb, lib/passageidentity/client.rb, tests/auth_test.rb
=> feat: reworks the new create magic link func into three separate functions

.github/workflows/release.yml
=> ci: add failure check for publish step before tagging

.github/workflows/release.yml
=> ci: set rubygems to latest

.github/workflows/release.yml
=> ci: fix setup-ruby inputs

passageidentity.gemspec
=> chore: update openssl to be compatible with rubygems bundler

lib/passageidentity/auth.rb, passageidentity.gemspec
=> chore: removes unused openssl dependency

release-please-config.json
=> ci: skip release-please tagging so rake can do it on publish

lib/passageidentity/user.rb
Returns `void` instead of `boolean` for `Client.user.delete`
=> feat!: return void instead of boolean

lib/passageidentity/auth.rb, lib/passageidentity/client.rb, tests/auth_test.rb
- requires kwargs for auth methods
- simplifies `fetch_jwks` helper method
- adds guard clause to magic link with user method
=> refactor: simplifies auth class code

Gemfile, passageidentity.gemspec
- updates deps to latest
- removes unused dev deps
=> chore: update deps to latest

.github/workflows/on-pull-request.yml, Gemfile
- removes unused secrets from env vars in CI
- removes unused dotenv dependency
=> ci: remove secrets from env vars
